version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    networks:
      - mongo_network
    volumes:
      - mongodb_data:/data/db
  nextjs:
    container_name: nextjs
    build:
      context: .
    ports:
      - "8080:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
    volumes:
      - ./public/uploads:/app/public/uploads:rw
    networks:
      - mongo_network
networks:
  mongo_network:
    driver: bridge
volumes:
  mongodb_data:
    driver: local