FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN chown -R 1000:1000 /app/public/uploads
# Accept build-time environment variables
ARG MONGODB_URI_ARG
ARG MONGO_ROOT_PASSWORD_ARG
ARG NEXT_PUBLIC_API_URL_ARG
ARG MONGO_ROOT_USERNAME_ARG
ARG JWT_SECRETE_STRING_ARG

# Set them as environment variables for runtime
ENV MONGODB_URI=$MONGODB_URI_ARG
ENV MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD_ARG
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL_ARG
ENV MONGO_ROOT_USERNAME=$MONGO_ROOT_USERNAME_ARG
ENV JWT_SECRETE_STRING=$JWT_SECRETE_STRING_ARG

# Debugging: Print env variables
RUN echo "MONGODB_URI: $MONGODB_URI"
RUN echo "NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL"
RUN echo "MONGO_ROOT_USERNAME: $MONGO_ROOT_USERNAME"
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]