version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=automobile
    ports:
      - "27018:27017"
    networks:
      - mongo_network
    volumes:
      - mongodb_data:/data/db

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
